# Generated by Django 4.0.4 on 2022-05-13 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_room_salesman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-created',), 'verbose_name': 'Чат', 'verbose_name_plural': 'Чат'},
        ),
    ]
